shops/cart/urls.py
#coding utf-8
#mojun

from django.conf.urls import url
from.import views

urlpatterns=[

    url(r'^cartadd/',views.cartadd,name='cartadd'),
    url(r'^cartshow/',views.cartshow,name='cartshow'),
    # url(r'^deletcart/(?P<pk>[0-9]+)',views.deletcart,name='deletcart'),
    #ajaxc
    url(r'^delcar/',views.delcar,name='delcar'),
    url(r'^changenum/',views.changenum,name='changenum'),
    url(r'^jiannum/',views.jiannum,name='jiannum'),



    url(r'^clearcart/',views.clearcart,name='clearcart'),

    #购物车的商品数量的加减，商品小计 ，商品总计
    url(r'^decgoodsnum/(?P<pk>[0-9]+)',views.decgoodsnum,name='decgoodsnum'),
    url(r'^addgoodsnum/(?P<pk>[0-9]+)',views.addgoodsnum,name='addgoodsnum'),


]

shops/goods/urls.py
#coding utf-8
#mojun

from django.conf.urls import url
from.import views

urlpatterns =[
    url(r'^goodsadd/$',views.goodsadd,name='goodsadd'),
    url(r'^goodstypeadd/',views.goodstypeadd,name='goodstypeadd'),
    url(r'^goodstypeaddDo/',views.goodstypeaddDo,name='goodstypeaddDo'),

    url(r'^goodsShow/$',views.goodsShow,name='goodsShow'),
    url(r'^delettype/(?P<pk>[0-9]+)',views.delettype,name='delettype'),
    url(r'^modlytype/(?P<pk>[0-9]+)',views.modlytype,name='modlytype'),
    url(r'^goodsmodlyDo/',views.goodsmodlyDo,name='goodsmodlyDo'),

    #商品进数据库
    url(r'^goodsadddo/',views.goodsadddo,name='goodsadddo'),


    url(r'^goodslist_show/',views.goodslist_show,name='goodslist_show'),

    url(r'^deletgoods/(?P<pk>[0-9]+)',views.deletgoods,name='deletgoods'),
    url(r'^modlygoods/(?P<pk>[0-9]+)',views.modlygoods,name='modlygoods'),

    url(r'^updatagoodsadddo/',views.updatagoodsadddo,name='updatagoodsadddo'),

    #鲜果列表
    url(r'^goodslist/',views.goodslist,name='goodslist'),
    url(r'^goodslist1/(?P<pk>[0-9]+)',views.goodslist1,name='goodslist1'),
    url(r'^goodslistss/(?P<type_id>[0-9]+)',views.goodslistss,name='goodslistss'),
    
    #商品下架
    url(r'^ishowx/(?P<pk>[0-9]+)',views.ishowx,name='ishowx'),
    #商品上架
    url(r'^ishows/(?P<pk>[0-9]+)',views.ishows,name='ishows'),




]

shops/shops/urls.py
from django.conf.urls import url,include
from.upload import upload_image
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^User/',include('users.urls',namespace='users')),
    url(r'^Goods/',include('goods.urls',namespace='goods')),

    #商家登入
    url(r'^seller/',include('seller.urls',namespace='seller')),

    url(r'^cart/',include('cart.urls',namespace='cart')), #购物车总路由

    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^openshop/',include('openshop.urls',namespace='openshop')),
    url(r'^store/',include('store.urls',namespace='store')),
    url(r'^admin/uploads/(?P<dir_name>[^/]+)$',upload_image,name="upload_image"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shops/users/urls.py
#coding utf-8
#mojun

from django.conf.urls import url

from.import views
urlpatterns = [
    url(r'^sign/',views.userSign,name="sign"), #注册会员
    url(r'^signdo/',views.userSigndo,name='signdo'),#注册的数据写进说一句库

    #email验证部分
    url(r'^UserEmail/',views.UserEmails,name='UserEmail'),

    url(r'^chakan_email/',views.chakan_email,name='chakan_email'),
    url(r'jihuo/',views.jihuo,name='jihuo'),
    url(r'^email_active/',views.email_active,name='email_active'),

    url(r'^login/',views.userLogin,name='login'),    #登入
    url(r'^logindo/',views.userLogindo,name='logindo'),
    url(r'^loginout/',views.loginout,name='loginout'),

    url(r'^main/',views.userMainPage,name='main'),   #登入成功的首页主页面


    # url(r'^carts/',views.userCart,name='carts'),   #购物车
    # url(r'^cartsdo',views.userCartsdo,name='cartsdo'),  #用户下单页面

    #商品详情页
    # url(r'^goods_introduce/',views.goods_introduce,name='goods_introduce'),

    #把数据传入商品详情页   一对一！
    # /(?P<seller_id>[0-9]+)这里加这个是为了对应index 加参数，seller_id 对应def goods_introduce(request,pk):
    #(request,pk,seller_id)  对应方法1
    url(r'^goods_introduce/(?P<pk>[0-9]+)',views.goods_introduce,name='goods_introduce'),

    url(r'^user_order/',views.user_order,name='user_order'),

    url(r'^user_base/',views.user_base,name='user_base'),


    url(r'users_orderdetails/(?P<pk>[0-9]+)/(?P<adress_id>[0-9]+)',views.users_orderdetails,name='users_orderdetails'),

    #收货
    url(r'^shouhuo/(?P<pk>[0-9]+)',views.shouhuo,name='shouhuo'),

    #个人资料修改
    url(r'^modifymessages/',views.modifymessages,name='modifymessages'),
    url(r'^modifymessagedo/',views.modifymessagedo,name='modifymessagedo'),

    #评论
    url(r'^commentgoodsadd/(?P<goods_id>[0-9]+)/(?P<seller_id>[0-9]+)',views.commentgoodsadd,name='commentgoodsadd'),
    
    url(r'^commentgoodsadddo/',views.commentgoodsadddo,name='commentgoodsadddo'),
    url(r'^get_valid_img/',views.get_valid_img,name='get_valid_img')



]

shops/goods/models.py
from django.db import models
from seller.models import sellerData
from openshop.models import openshopdata
# Create your models here.

class goods_type(models.Model):
    type_id=models.AutoField(auto_created=True,primary_key=True,db_column='type_id')
    type_name=models.CharField(max_length=30,null=False,db_column='type_name')
    openshop = models.ForeignKey(openshopdata, db_column='openshop_id', default='')
    seller = models.ForeignKey(sellerData, db_column='seller_id',default='')
    add_time = models.DateTimeField(null=True, db_column='add_time')



class goods(models.Model):
    goods_id = models.AutoField(auto_created=True,primary_key=True,db_column='goods_id')
    goods_num = models.CharField(max_length=30,null=False,db_column='goods_num')
    goods_name = models.CharField(max_length=100,null=False,db_column='goods_name')

    type = models.ForeignKey(goods_type,db_column='type_id')

    goods_oprice = models.FloatField(null=False,db_column='goods_oprice')
    goods_xprice = models.FloatField(null=False,db_column='goods_xprice')
    goods_count = models.IntegerField(null=False,db_column='goods_count')
    goods_method = models.CharField(null=False,db_column='goods_method',max_length=100)
    goods_infro = models.CharField(null=False,max_length=200,db_column='goods_infro')
    goods_ishow = models.IntegerField(null=False,db_column='goods_ishow')

    goods_pic = models.ImageField(default="",upload_to="media/uploads")
    
    goods_address = models.CharField(max_length=50,null=False,db_column='goods_address')
    goods_body = models.TextField(null=False,db_column='goods_body')

    seller = models.ForeignKey(sellerData,db_column='seller_id')

    up_time = models.DateTimeField(null=False,db_column='up_time')
    down_time = models.DateTimeField(null=True,db_column='down_time')

    # 购物车需要店铺id
    openshop = models.ForeignKey(openshopdata, db_column='openshop_id',default='')

shops/goods/views.py
from django.shortcuts import render
from.models import goods_type ,goods,sellerData
from django.http import HttpResponseRedirect,HttpResponse
import datetime
from django.conf import settings
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
# Create your views here.

def goodsadd(request):

    list=goods_type.objects.order_by('-type_id')
    return render(request,'goods/goodsAdd.html',{"list":list})


def goodstypeadd(request):
    type = goods_type.objects.all()
    return render(request,'goods/goodstypeadd.html',{"type":type})

def goodstypeaddDo(request):
    type_name=request.POST['type_name']
    openshop_id = request.session.get('openshop_id')
    add_time=datetime.datetime.now()

    type=goods_type.objects.create(
        type_name=type_name,
        openshop_id=openshop_id,
        add_time=add_time,
    )
    if type:
       # return HttpResponse('ok')
        return HttpResponseRedirect('/Goods/goodsShow')
    else:
        return HttpResponse('erro')


def goodsShow(request):
    seller_id=request.session['seller_id']
    openshop_id=request.session['openshop_id']
    list=goods_type.objects.order_by('-type_id')
    return render(request,'goods/goodsshow.html',{"list":list})


def delettype(request,pk):
    list=goods_type.objects.get(pk=pk)
    list.delete()
    return HttpResponseRedirect("/Goods/goodsShow")

def modlytype(request,pk):
    list=goods_type.objects.get(pk=pk)
    return render(request,'goods/goodsmodly.html',{'list':list})


def goodsmodlyDo(request):
    type_name = request.POST['type_name']
    type_id=request.POST['type_id']
    ret=goods_type.objects.filter(type_id=type_id).update(type_name=type_name)
    if ret:
        return HttpResponseRedirect('/Goods/goodsShow')
    else:
        return HttpResponse('erro!')

    
def goodsadddo(request):
    openshop_id = request.session.get('openshop_id')
    goods_num=request.POST['goods_num']
    goods_name=request.POST['goods_name']
    # type=goods.seller.seller_id
    type_id=request.POST['type_id']
    goods_oprice=request.POST['goods_oprice']
    goods_xprice=request.POST['goods_xprice']
    goods_count=request.POST['goods_count']
    goods_method=request.POST['goods_method']
    goods_infro=request.POST['goods_infro']

    goods_ishow=request.POST['goods_ishow']

    goods_address=request.POST['goods_address']
    goods_body=request.POST['goods_content']
    up_time=datetime.datetime.now()
    seller_id=request.session.get('seller_id')
    goods_pic = request.FILES['goods_pic']


    save_path = '%s/media/uploads/%s' % (settings.MEDIA_ROOT,goods_pic.name)
    with open(save_path,'wb')as f:
        for content in goods_pic.chunks():
            f.write(content)

    ress=goods.objects.create(

                              goods_num=goods_num,
                              goods_name=goods_name,
                              type_id=type_id,
                              goods_oprice=goods_oprice,
                              goods_xprice=goods_xprice,
                              goods_count=goods_count,
                              goods_method=goods_method,
                              goods_infro=goods_infro,
                              goods_ishow=goods_ishow,
                              goods_address=goods_address,
                              goods_body=goods_body,
                              seller_id=seller_id,
                              up_time=up_time,
                              goods_pic='media/uploads/%s' % goods_pic.name,
        openshop_id=openshop_id
                              )
    if ress:
        return HttpResponseRedirect('/Goods/goodslist_show')
        # return HttpResponse('1231')
    else:
        return HttpResponse('添加失败！')

#商品列表
def goodslist_show(request):
    seller_id=request.session['seller_id']
    openshop_id=request.session['openshop_id']
    list=goods.objects.filter(seller_id=seller_id,openshop_id=openshop_id).order_by('-pk')

    # django的分布器
    # 1.分页器 分谁 一页显示几条数据，如果没有获取默认值是1
    paginator = Paginator(list, 3)
    page = request.GET.get("page", 1)
    # 吧当前页变成整数
    Current = int(page)
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果输入的页码不是整数
    except EmptyPage:
        # 如果输入的页码是一个空页 最大页
        list = paginator.page(paginator.num_pages)

    return render(request,'goods/goodslist_show.html',locals())




def deletgoods(request,pk):
    list=goods.objects.get(pk=pk)
    list.delete()
    return HttpResponseRedirect("/Goods/goodslist_show")

def modlygoods(request,pk):
    signle =goods.objects.get(pk=pk)
    typelist = goods_type.objects.all()
    # picimg=goods.objects.all()
    return render(request,'goods/uptadagoodsAdd.html',{'signle':signle,"typelist":typelist})


def updatagoodsadddo(request):
    goods_id=request.POST['goods_id']
    goods_num=request.POST['goods_num']
    goods_name=request.POST['goods_name']
    # type=goods.seller.seller_id
    type_id=request.POST['type_id']
    goods_oprice=request.POST['goods_oprice']
    goods_xprice=request.POST['goods_xprice']
    goods_count=request.POST['goods_count']
    goods_method=request.POST['goods_method']
    goods_infro=request.POST['goods_infro']
    goods_ishow=request.POST['goods_ishow']
    goods_address=request.POST['goods_address']
    goods_body=request.POST['goods_content']
    up_time=datetime.datetime.now()
    seller_id=request.session.get('seller_id')
    goods_pic = request.FILES['goods_pic']
    save_path = '%s/media/uploads/%s' % (settings.MEDIA_ROOT,goods_pic.name)
    with open(save_path,'wb')as f:
        for content in goods_pic.chunks():
            f.write(content)
    ress=goods.objects.filter(goods_id=goods_id).update(

                              goods_num=goods_num,
                              goods_name=goods_name,
                              type_id=type_id,
                              goods_oprice=goods_oprice,
                              goods_xprice=goods_xprice,
                              goods_count=goods_count,
                              goods_method=goods_method,
                              goods_infro=goods_infro,
                              goods_ishow=goods_ishow,
                              goods_address=goods_address,
                              goods_body=goods_body,
                              seller_id=seller_id,
                              up_time=up_time,
                              goods_pic='media/uploads/%s' % goods_pic.name,
                              )
    if ress:
        return HttpResponseRedirect('/Goods/goodslist_show')
        # return HttpResponse('1231')
    else:
        return HttpResponse('修改失败！')


# 鲜果列表的逻辑代码
def goodslist(request):
#直接把goods表的数据倒过来就可以啦
    list1=goods_type.objects.all() #包括了type_id 
    list=goods.objects.filter(goods_ishow=1).order_by('-goods_id').all()



# django的分布器
    # 1.分页器 分谁 一页显示几条数据，如果没有获取默认值是1
    paginator = Paginator(list,10)
    page = request.GET.get("page",1)
    # 吧当前页变成整数
    Current = int(page)
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果输入的页码不是整数
    except EmptyPage:
        # 如果输入的页码是一个空页 最大页
        list = paginator.page(paginator.num_pages)

    return render(request,'goods/allindex.html',locals(),{"list1":list1})

def goodslistss(request,type_id) :
    list = goods.objects.filter(goods_ishow=1,type_id=type_id).order_by('-goods_id').all()
    return render(request, 'goods/allindex.html', locals(), {"list": list})

def goodslist1(request,pk):
    list1 = goods_type.objects.all()
    list = goods.objects.filter(goods_ishow=1,type_id=pk).order_by('-goods_id').all()
    # list=goods.objects.filter(type_id=pk).all()
    # django的分布器
    # 1.分页器 分谁 一页显示几条数据，如果没有获取默认值是1
    paginator = Paginator(list, 10)
    page = request.GET.get("page", 1)
    # 吧当前页变成整数
    Current = int(page)
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果输入的页码不是整数
    except EmptyPage:
        # 如果输入的页码是一个空页 最大页
        list = paginator.page(paginator.num_pages)

    return render(request, 'goods/allindex.html', locals(), {"list1": list1})


#商品上下架
def ishowx(request,pk):
    down_time = datetime.datetime.now()
    res=goods.objects.filter(pk=pk).update(goods_ishow=0,down_time=down_time)
    if res:
        return HttpResponseRedirect('/Goods/goodslist_show/')
def ishows(request,pk):
    up_time=datetime.datetime.now()
    res = goods.objects.filter(pk=pk).update(goods_ishow=1,up_time=up_time)
    if res:
        return HttpResponseRedirect('/Goods/goodslist_show/')
    
        

shops/templates/goods/allindex.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        #da_da a {
            font-family: 微软雅黑;
            color: #449d44;
            font-size: 15px;
            text-align: center;
        }
    </style>

    <div class="body">
        <ul>

            <li id="da"><img src="{% static 'images/002.jpg' %}" alt="">
            </li>

            <div id="da_da">类别：
                {% for foo in list1 %}
                    <a href="{% url 'goods:goodslist1' foo.type_id %}">{{ foo.type_name }}</a>

{#                    <select id="myselect" name="myselect">#}
{##}
{#                        <option value="">全部</option>#}
{##}
{#                        <option value="3">国产</option>#}
{##}
{#                        <option value="4">进口</option>#}
{#                    </select>#}
{##}
{#                    <script type="text/javascript">#}
{#                        $(function () {#}
{#                            $('#myselect').change(function () {#}
{#                                window.location.href = "/goods/goodslist1/" + $(this).val()#}
{#                            })#}
{#                        })#}
{#                    </script>#}


                {% endfor %}
            </div>

            {% for f in list %}
                {#              为了获取卖家id 为了评论里用  seller_id#}
                {#                #这里加了f.seller_id,为了去 def goods_introduce(request,pk): 的方法1#}
                <li><a href="{% url 'users:goods_introduce' f.goods_id %}"><img src="{% static f.goods_pic %}"
                                                                                alt=""></a>
                    <p><a href="{% url 'users:goods_introduce' f.goods_id %}">{{ f.goods_name }}</a></p>
                    <p style="">￥{{ f.goods_xprice }}元<s>￥{{ f.goods_oprice }}元</s></p>
                </li>
            {% endfor %}

        </ul>

    </div>


    <div>
        <ul class="pagination">
            {#                        #上一页情况#}
            {% if list.has_previous %}
                <li><a href="/Goods/goodslist?page={{ list.previous_page_number }}">上一页</a></li>
            {% else %}
                <li class="disabled"><a href="#">上一页</a></li>
            {% endif %}
            {#                      #中间部分#}
            {% for num in list.paginator.page_range %}
                {% if num == Current %}
                    <li class="active"><a href="/Goods/goodslist?page={{ num }}">{{ num }}</a></li>
                {% else %}
                    <li><a href="/Goods/goodslist?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if list.has_next %}
                <li><a href="/Goods/goodslist?page={{ list.next_page_number }}">下一页</a></li>
            {% else %}
                <li class="disabled"><a href="">下一页</a></li>
            {% endif %}

        </ul>

    </div>





{% endblock %}

shops/templates/goods/goodsAdd.html
{% extends 'base/base_seller.html' %}
{% block mess %}
   <div class="x-body layui-anim layui-anim-up">
        <form class="layui-form" method="post" action="{% url 'goods:goodsadddo' %}" enctype="multipart/form-data">
        {% csrf_token %}
          <div class="layui-form-item">
              <label for="L_email" class="layui-form-label">
                  <span class="x-red">*</span>商品编号
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_email" name="goods_num" required=""
                  autocomplete="off" class="layui-input">
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_username" class="layui-form-label">
                  <span class="x-red">*</span>商品名称
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_username" name="goods_name" required=""
                  autocomplete="off" class="layui-input">
              </div>
          </div>

            <div class="layui-form-item">
              <label for="L_username" class="layui-form-label">
                  <span class="x-red">*</span>商品类型
              </label>
              <div class="layui-input-inline">
                  <select name="type_id">
                      {% for j in list %}
                      <option value="{{ j.type_id }}">{{ j.type_name }}</option>
                      {% endfor %}
                  </select>
              </div>
          </div>

          <div class="layui-form-item">
              <label for="L_pass" class="layui-form-label">
                  <span class="x-red">*</span>商品原价
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_pass" name="goods_oprice" required=""
                  autocomplete="off" class="layui-input">
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
                  <span class="x-red">*</span>商品现价
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_repass" name="goods_xprice" required=""
                  autocomplete="off" class="layui-input">
              </div>
          </div>
		  <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
                  <span class="x-red">*</span>商品库存
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_repass" name="goods_count" required=""
                  autocomplete="off" class="layui-input">
              </div>
          </div>
		  <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
                  <span class="x-red">*</span>存储方法
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_repass" name="goods_method" required=""
                  autocomplete="off" class="layui-input">
              </div>
          </div>
		  <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
                  <span class="x-red">*</span>商品介绍
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_repass" name="goods_infro" required=""
                  autocomplete="off" class="layui-input">
              </div>
          </div>
{#              #上架#}
            <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
                  <span class="x-red">*</span>是否上架
              </label>
              <div class="layui-input-inline">
                  <a href="#"><input type="radio" id="L_repass" name="goods_ishow" required=""
                  autocomplete="off" class="layui-input" value="1">是</a>&nbsp;&nbsp;&nbsp;&nbsp;
                  <a href="#"><input type="radio" id="L_repass" name="goods_ishow" required=""
                  autocomplete="off" class="layui-input" value="0">否</a>
              </div>
            </div>




		  <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
                  <span class="x-red">*</span>商品缩略图
              </label>
              <div class="layui-input-inline">
                  <input type="file" id="L_repass" name="goods_pic" required=""
                  autocomplete="off" class="layui-input">
              </div>
          </div>
		  <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
                  <span class="x-red">*</span>配送地址
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_repass" name="goods_address" required=""
                  autocomplete="off" class="layui-input">
              </div>
          </div>
		  <div class="layui-form-item layui-form-text">
                    <label for="desc" class="layui-form-label">
                        商品内容
                    </label>
                    <div class="layui-input-block">
                        <textarea placeholder="请输入内容" id="desc" name="goods_content" class="layui-textarea"></textarea>

                        <script>
                            KindEditor.ready(function (res) {
                                res.create("textarea[name=goods_content]",{
                                    width:"600px",
                                    height:"300px",
                                    uploadJson:"/admin/uploads/kindeditor"
                                })

                            })
                        </script>
                    </div>

                </div>
          <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
              </label>
              <button  class="layui-btn" lay-filter="add" lay-submit="">
                  增加
              </button>

          </div>
      </form>
    </div>
{% endblock %}

shops/templates/goods/goodslist_show.html
{% extends 'base/base_seller.html' %}
 {% load static %}
{% block mess %}
 <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">商品管理</a>
        <a href="">商品列表</a>
      </span>
    </div>
    <div class="x-body">
      <table class="layui-table">
        <thead>
          <tr>
		    <th>商品id</th>
            <th>商品图片</th>
            <th>商品编号</th>
            <th>商品名称</th>
            <th>商品原价</th>
            <th>商品现价</th>
            <th>商品库存</th>
			<th>商品存储方法</th>
            <th>是否上架</th>
            <th>操作</th>
			</tr>
        </thead>
        <tbody>
        {% for foo in list %}

          <tr>
            <td>{{ foo.goods_id }}</td>
            <td><img src="{% static foo.goods_pic %}" alt=""></td>
			<td>{{ foo.goods_num }}</td>
            <td>{{ foo.goods_name }}</td>
            <td>{{ foo.goods_oprice }}</td>
            <td>{{ foo.goods_xprice }}</td>
            <td>{{ foo.goods_count }}</td>
			<td>{{ foo.goods_method }}</td>
            <td>{{ foo.goods_ishow }}</td>
            <td >
				<a href="{% url 'goods:modlygoods' foo.goods_id %}">编辑</a>
                <a href="{% url 'goods:deletgoods' foo.goods_id %}">删除</a>
                    {% if foo.goods_ishow == 1  %}
                        <a href="{% url 'goods:ishowx' foo.goods_id  %}">下架</a>
                    {% else  %}
                        <a href="{% url 'goods:ishows' foo.goods_id  %}">上架</a>
                    {% endif %}
                <a href="{% url 'users:goods_introduce' foo.goods_id %}">查看评价信息</a>
            </td>
          </tr>
          {% empty %}
            <tr>
                <td colspan="9" align="center">暂无商品</td>
            </tr>


        {% endfor %}

{#添加上下页功能       t#}
        <tr>
                <td colspan="9">
                    <ul class="pagination">
{#                        #上一页情况#}
                    {% if list.has_previous %}
                        <li><a href="/Goods/goodslist_show?page={{ list.previous_page_number }}">上一页</a></li>
                    {% else %}
                        <li class="disabled"><a href="#">上一页</a></li>
                    {% endif %}
{#                      #中间部分#}
                    {% for num in list.paginator.page_range %}
                    {% if num == Current %}
                        <li class="active"><a href="/Goods/goodslist_show?page={{ num }}">{{ num }}</a></li>
                    {% else %}
                        <li><a href="/Goods/goodslist_show?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                    {% endfor %}

                    {% if list.has_next %}
                        <li><a href="/Goods/goodslist_show?page={{ list.next_page_number }}">下一页</a></li>
                    {% else %}
                        <li class="disabled"><a href="">下一页</a></li>
                    {% endif %}

                    </ul>

                </td>
            </tr>




        </tbody>
      </table>

    </div>


{% endblock %}

shops/templates/goods/goodsshow.html
{% extends 'base/base_seller.html' %}

{% block mess %}
 <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="#">商品管理</a>
        <a href="{% url 'goods:goodsadd' %}">增加类型</a>
      </span>
    </div>
    <div class="x-body">
      <table class="layui-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>分类名</th>

            <th>操作</th>
        </thead>
        <tbody>

          {% for i in list %}
          <tr>
            <td>{{ i.type_id }}</td>
			<td>{{ i.type_name }}</td>

            <td><a href="{% url 'goods:modlytype' i.type_id %}">编辑</a>
                <a href="{% url 'goods:delettype' i.type_id %}">删除</a>
            </td>
          </tr>
              {% empty %}
          <tr>
            <td colspan="3" align="center">暂无商品类型</td>
          </tr>
           {% endfor %}

        </tbody>
      </table>
    </div>




{% endblock %}