shops/cart/urls.py
#coding utf-8
#mojun

from django.conf.urls import url
from.import views

urlpatterns=[

    url(r'^cartadd/',views.cartadd,name='cartadd'),
    url(r'^cartshow/',views.cartshow,name='cartshow'),
    # url(r'^deletcart/(?P<pk>[0-9]+)',views.deletcart,name='deletcart'),
    #ajaxc
    url(r'^delcar/',views.delcar,name='delcar'),
    url(r'^changenum/',views.changenum,name='changenum'),
    url(r'^jiannum/',views.jiannum,name='jiannum'),



    url(r'^clearcart/',views.clearcart,name='clearcart'),

    #购物车的商品数量的加减，商品小计 ，商品总计
    url(r'^decgoodsnum/(?P<pk>[0-9]+)',views.decgoodsnum,name='decgoodsnum'),
    url(r'^addgoodsnum/(?P<pk>[0-9]+)',views.addgoodsnum,name='addgoodsnum'),


]

shops/goods/urls.py
#coding utf-8
#mojun

from django.conf.urls import url
from.import views

urlpatterns =[
    url(r'^goodsadd/$',views.goodsadd,name='goodsadd'),
    url(r'^goodstypeadd/',views.goodstypeadd,name='goodstypeadd'),
    url(r'^goodstypeaddDo/',views.goodstypeaddDo,name='goodstypeaddDo'),

    url(r'^goodsShow/$',views.goodsShow,name='goodsShow'),
    url(r'^delettype/(?P<pk>[0-9]+)',views.delettype,name='delettype'),
    url(r'^modlytype/(?P<pk>[0-9]+)',views.modlytype,name='modlytype'),
    url(r'^goodsmodlyDo/',views.goodsmodlyDo,name='goodsmodlyDo'),

    #商品进数据库
    url(r'^goodsadddo/',views.goodsadddo,name='goodsadddo'),


    url(r'^goodslist_show/',views.goodslist_show,name='goodslist_show'),

    url(r'^deletgoods/(?P<pk>[0-9]+)',views.deletgoods,name='deletgoods'),
    url(r'^modlygoods/(?P<pk>[0-9]+)',views.modlygoods,name='modlygoods'),

    url(r'^updatagoodsadddo/',views.updatagoodsadddo,name='updatagoodsadddo'),

    #鲜果列表
    url(r'^goodslist/',views.goodslist,name='goodslist'),
    url(r'^goodslist1/(?P<pk>[0-9]+)',views.goodslist1,name='goodslist1'),
    url(r'^goodslistss/(?P<type_id>[0-9]+)',views.goodslistss,name='goodslistss'),
    
    #商品下架
    url(r'^ishowx/(?P<pk>[0-9]+)',views.ishowx,name='ishowx'),
    #商品上架
    url(r'^ishows/(?P<pk>[0-9]+)',views.ishows,name='ishows'),




]

shops/seller/urls.py
#coding utf-8
#mojun
from django.conf.urls import url

from.import views

urlpatterns = [
    # 商家登入
    url(r'^sellerLogin/$', views.sellerLogin, name='sellerLogin'),
    url(r'^sellerLogindo/$', views.sellerLogindo, name='sellerLogindo'),
    url(r'^sellerout/',views.sellerout,name='sellerout'),

    url(r'^sellerMina/(?P<pk>[0-9]+)',views.sellerMina,name='sellerMina'),
    url(r'^showorder/',views.showorder,name='showorder'),

    #会员中心的会员列表
    url(r'^huiyuan/',views.huiyuan,name='huiyuan'),

    url(r'^show_xiangqing/(?P<pk>[0-9]+)/(?P<adress_id>[0-9]+)',views.show_xiangqing,name='show_xiangqing'),
    # url(r'^show_xiangqing/',views.show_xiangqing,name='show_xiangqing')

#收货
    url(r'^fahuo/(?P<pk>[0-9]+)',views.fahuo,name='fahuo'),

    url(r'^seller_chakan_comment/(?P<pk>[0-9]+)',views.seller_chakan_comment,name='seller_chakan_comment'),

    #卖家店铺
    url(r'^store_list/',views.store_list,name='store_list'),


    #已有店铺的卖家开店
    url(r'^store/',views.store,name='store'),

    #卖家再开店的数据写进openshopdata数据库
    url(r'^storedo',views.storedo,name='storedo'),

    #邮件的发送
    url(r'^sendemail/(?P<pk>[0-9]+)',views.sendemail,name='sendemail'),
    url(r'^sendemaildo/',views.sendemaildo,name='sendemaildo'),



    #后台权限分配
    url(r'^management/',views.management,name='management'),
    url(r'^poweradd/',views.poweradd,name='poweradd'),
    url(r'^dopower/',views.dopower,name='dopower'),
    url(r'^delpower/',views.delpower,name='delpower'),



    # 后台角色分配
    url(r'^roles/', views.roles, name='roles'),
    url(r'^roleadd/', views.roleadd, name='roleadd'),
    url(r'^dorole/', views.dorole, name='dorole'),
    url(r'^delrole/', views.delrole, name='delrole')





]

shops/shops/urls.py
from django.conf.urls import url,include
from.upload import upload_image
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^User/',include('users.urls',namespace='users')),
    url(r'^Goods/',include('goods.urls',namespace='goods')),

    #商家登入
    url(r'^seller/',include('seller.urls',namespace='seller')),

    url(r'^cart/',include('cart.urls',namespace='cart')), #购物车总路由

    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^openshop/',include('openshop.urls',namespace='openshop')),
    url(r'^store/',include('store.urls',namespace='store')),
    url(r'^admin/uploads/(?P<dir_name>[^/]+)$',upload_image,name="upload_image"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shops/users/urls.py
#coding utf-8
#mojun

from django.conf.urls import url

from.import views
urlpatterns = [
    url(r'^sign/',views.userSign,name="sign"), #注册会员
    url(r'^signdo/',views.userSigndo,name='signdo'),#注册的数据写进说一句库

    #email验证部分
    url(r'^UserEmail/',views.UserEmails,name='UserEmail'),

    url(r'^chakan_email/',views.chakan_email,name='chakan_email'),
    url(r'jihuo/',views.jihuo,name='jihuo'),
    url(r'^email_active/',views.email_active,name='email_active'),

    url(r'^login/',views.userLogin,name='login'),    #登入
    url(r'^logindo/',views.userLogindo,name='logindo'),
    url(r'^loginout/',views.loginout,name='loginout'),

    url(r'^main/',views.userMainPage,name='main'),   #登入成功的首页主页面


    # url(r'^carts/',views.userCart,name='carts'),   #购物车
    # url(r'^cartsdo',views.userCartsdo,name='cartsdo'),  #用户下单页面

    #商品详情页
    # url(r'^goods_introduce/',views.goods_introduce,name='goods_introduce'),

    #把数据传入商品详情页   一对一！
    # /(?P<seller_id>[0-9]+)这里加这个是为了对应index 加参数，seller_id 对应def goods_introduce(request,pk):
    #(request,pk,seller_id)  对应方法1
    url(r'^goods_introduce/(?P<pk>[0-9]+)',views.goods_introduce,name='goods_introduce'),

    url(r'^user_order/',views.user_order,name='user_order'),

    url(r'^user_base/',views.user_base,name='user_base'),


    url(r'users_orderdetails/(?P<pk>[0-9]+)/(?P<adress_id>[0-9]+)',views.users_orderdetails,name='users_orderdetails'),

    #收货
    url(r'^shouhuo/(?P<pk>[0-9]+)',views.shouhuo,name='shouhuo'),

    #个人资料修改
    url(r'^modifymessages/',views.modifymessages,name='modifymessages'),
    url(r'^modifymessagedo/',views.modifymessagedo,name='modifymessagedo'),

    #评论
    url(r'^commentgoodsadd/(?P<goods_id>[0-9]+)/(?P<seller_id>[0-9]+)',views.commentgoodsadd,name='commentgoodsadd'),
    
    url(r'^commentgoodsadddo/',views.commentgoodsadddo,name='commentgoodsadddo'),
    url(r'^get_valid_img/',views.get_valid_img,name='get_valid_img')



]

shops/templates/base/base_seller.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>全球生鲜卖家管理后台页面</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />

    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/css/font.css' %}">
	<link rel="stylesheet" href="{% static 'css/css/xadmin.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    
    <script type="text/javascript" src="{% static 'js/js/jquery.min.js' %}"></script>
    <script src="{% static 'lib/layui/layui.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.js' %}"></script>
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>

</head>
<body>
{% block mess %}

{% endblock %}

</body>
</html>

shops/templates/base/foot_seller.html
{% load static from staticfiles %}

<div class="footer">
        <div class="copyright">Copyright ©2018 全球生鲜卖家管理后台 v2.5 All Rights Reserved</div>
    </div>

shops/templates/base/left.html
{% load static from staticfiles %}

 <div class="left-nav">
      <div id="side-nav">
        <ul id="nav">
            <li>
                <a href="javascript:;">
                    <i class="iconfont">&#xe6b8;</i>
                    <cite>商品管理</cite>
                    <i class="iconfont nav_right">&#xe697;</i>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a _href="{% url 'goods:goodslist_show' %}">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>商品列表</cite>

                        </a>
                    </li >
                    <li>
                        <a _href="{% url 'goods:goodsadd' %}">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>商品添加</cite>

                        </a>
                    </li>

                    <li>
                        <a _href="{% url 'goods:goodstypeadd' %}">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>商品类型添加</cite>

                        </a>
                    </li>

                    <li>
                        <a _href="{% url 'goods:goodsShow' %}">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>商品类型列表</cite>

                        </a>
                    </li>

                    

                </ul>
            </li>
            
            <li>
                <a href="javascript:;">
                    <i class="iconfont">&#xe6b8;</i>
                    <cite>订单管理</cite>
                    <i class="iconfont nav_right">&#xe697;</i>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a _href="{% url 'seller:showorder' %}">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>订单列表</cite>

                        </a>
                    </li >
                </ul>
            </li>





            <li>
                <a href="javascript:;">
                    <i class="iconfont">&#xe6b8;</i>
                    <cite>会员中心</cite>
                    <i class="iconfont nav_right">&#xe697;</i>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a _href="{% url 'seller:huiyuan' %}">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>会员列表</cite>

                        </a>
                    </li >
                </ul>
            </li>


              <li>
                <a href="javascript:;">
                    <i class="iconfont">&#xe6b8;</i>
                    <cite>管理分配</cite>
                    <i class="iconfont nav_right">&#xe697;</i>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a _href="{% url 'seller:management' %}">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>权限管理</cite>

                        </a>
                    </li >
                </ul>

                   <ul class="sub-menu">
                    <li>
                        <a _href="{% url 'seller:roles' %}">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>角色列表</cite>

                        </a>
                    </li >
                </ul>

                    <ul class="sub-menu">
                    <li>
                        <a _href="">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>权限列表</cite>

                        </a>
                    </li >
                </ul>
            </li>







        </ul>
      </div>
    </div>
    <!-- <div class="x-slide_left"></div> -->

shops/templates/base/right.html
{% load static from staticfiles %}

<div class="page-content">
        <div class="layui-tab tab" lay-filter="xbs_tab" lay-allowclose="false">
          <ul class="layui-tab-title">
            <li class="home"><i class="layui-icon">&#xe68e;</i>我的桌面</li>
          </ul>
          <div class="layui-tab-content">
            <div class="layui-tab-item layui-show">

                 <blockquote class="layui-elem-quote">欢迎管理员：
            <span class="x-red">{{ request.session.sename }}</span>！当前时间:<span id="data_dq">2018-04-25 20:50:53</span>
                 </blockquote>
        <fieldset class="layui-elem-field">
            <legend>数据统计</legend>
            <div class="layui-field-box">
                <div class="layui-col-md12">
                    <div class="layui-card">
                        <div class="layui-card-body">
                            <div class="layui-carousel x-admin-carousel x-admin-backlog" lay-anim="" lay-indicator="inside" lay-arrow="none" style="width: 100%; height: 90px;">
                                <div carousel-item="">
                                    <ul class="layui-row layui-col-space10 layui-this">
                                        <li class="layui-col-xs2">
                                            <a href="javascript:;" class="x-admin-backlog-body">
                                                <h3>会员数</h3>
                                                <p>
                                                    <cite>12</cite></p>
                                            </a>
                                        </li>
                                        <li class="layui-col-xs2">
                                            <a href="javascript:;" class="x-admin-backlog-body">
                                                <h3>商品数</h3>
                                                <p>
                                                    <cite>67</cite></p>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>

        <fieldset class="layui-elem-field">
            <legend>系统信息</legend>
            <div class="layui-field-box">
                <table class="layui-table">
                    <tbody>
                        <tr>
                            <th>创作者</th>
                            <td>杨默军</td></tr>
                        <tr>
                            <th>全球生鲜店铺版本</th>
                            <td>1.0.180420</td></tr>
                        <tr>
                            <th>服务器地址</th>
                            <td>localhost</td></tr>
                        <tr>
                            <th>操作系统</th>
                            <td>WINNT</td></tr>
                            <th>django版本</th>
                            <td>1.11.3</td></tr>
                        <tr>
                            <th>创作时间</th>
                            <td>2018/12</td></tr>
                    </tbody>
                </table>
            </div>
        </fieldset>

    </div>
            </div>
          </div>
        </div>
    </div>
    <div class="page-content-bg"></div>

shops/templates/base/top_seller.html
{% load static from staticfiles %}
<div class="container">
   <div class="logo"><a href="./index.html">全球生鲜卖家管理后台</a></div>
   <div class="left_open">
        <i title="展开左侧栏" class="iconfont">&#xe699;</i>
   </div>
   <ul class="layui-nav right" lay-filter="">
       <li class="layui-nav-item">
            <a href="javascript:;">{{ request.session.sename }}</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
              <dd><a href="{% url 'seller:store_list' %}">切换店铺</a></dd>
              <dd><a href="{% url 'seller:sellerout' %}">退出</a></dd>
            </dl>
       </li>
       <li class="layui-nav-item to-index"><a href="{% url 'users:main' %}">前台首页</a></li>
   </ul>

</div>