shops/cart/urls.py
#coding utf-8
#mojun

from django.conf.urls import url
from.import views

urlpatterns=[

    url(r'^cartadd/',views.cartadd,name='cartadd'),
    url(r'^cartshow/',views.cartshow,name='cartshow'),
    # url(r'^deletcart/(?P<pk>[0-9]+)',views.deletcart,name='deletcart'),
    #ajaxc
    url(r'^delcar/',views.delcar,name='delcar'),
    url(r'^changenum/',views.changenum,name='changenum'),
    url(r'^jiannum/',views.jiannum,name='jiannum'),



    url(r'^clearcart/',views.clearcart,name='clearcart'),

    #购物车的商品数量的加减，商品小计 ，商品总计
    url(r'^decgoodsnum/(?P<pk>[0-9]+)',views.decgoodsnum,name='decgoodsnum'),
    url(r'^addgoodsnum/(?P<pk>[0-9]+)',views.addgoodsnum,name='addgoodsnum'),


]

shops/goods/urls.py
#coding utf-8
#mojun

from django.conf.urls import url
from.import views

urlpatterns =[
    url(r'^goodsadd/$',views.goodsadd,name='goodsadd'),
    url(r'^goodstypeadd/',views.goodstypeadd,name='goodstypeadd'),
    url(r'^goodstypeaddDo/',views.goodstypeaddDo,name='goodstypeaddDo'),

    url(r'^goodsShow/$',views.goodsShow,name='goodsShow'),
    url(r'^delettype/(?P<pk>[0-9]+)',views.delettype,name='delettype'),
    url(r'^modlytype/(?P<pk>[0-9]+)',views.modlytype,name='modlytype'),
    url(r'^goodsmodlyDo/',views.goodsmodlyDo,name='goodsmodlyDo'),

    #商品进数据库
    url(r'^goodsadddo/',views.goodsadddo,name='goodsadddo'),


    url(r'^goodslist_show/',views.goodslist_show,name='goodslist_show'),

    url(r'^deletgoods/(?P<pk>[0-9]+)',views.deletgoods,name='deletgoods'),
    url(r'^modlygoods/(?P<pk>[0-9]+)',views.modlygoods,name='modlygoods'),

    url(r'^updatagoodsadddo/',views.updatagoodsadddo,name='updatagoodsadddo'),

    #鲜果列表
    url(r'^goodslist/',views.goodslist,name='goodslist'),
    url(r'^goodslist1/(?P<pk>[0-9]+)',views.goodslist1,name='goodslist1'),
    url(r'^goodslistss/(?P<type_id>[0-9]+)',views.goodslistss,name='goodslistss'),
    
    #商品下架
    url(r'^ishowx/(?P<pk>[0-9]+)',views.ishowx,name='ishowx'),
    #商品上架
    url(r'^ishows/(?P<pk>[0-9]+)',views.ishows,name='ishows'),




]

shops/order/urls.py
#coding utf-8
#mojun

from django.conf.urls import url

from.import views

urlpatterns=[
    url(r'^ordershow',views.ordershow,name='ordershow'),
    # url(r'^orderadd/',views.orderadd,name='orderadd')
    url(r'^order_adress/',views.order_adress,name='order_adress'),
    url(r'^order_adressdo/',views.order_adressdo,name='order_adressdo'),
    url(r'^addto',views.addto,name='addto'),

    url(r'^comitdo/',views.comitdo,name='comitdo'),
    #下单成功后的路由
    url(r'^chakan_order/',views.chakan_order,name='chakan_order'),

    #查看订单的带参数路由
    url(r'^chakan_ordertit/(?P<pk>[0-9]+)',views.chakan_ordertit,name='chakan_ordertit'),



    # 订单的状态路径
    # url(r'^ordertatus/',views.ordertatus,name='ordertatus'),

    url(r'^payorder/',views.payorder,name='payorder'),

    
]

shops/shops/urls.py
from django.conf.urls import url,include
from.upload import upload_image
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^User/',include('users.urls',namespace='users')),
    url(r'^Goods/',include('goods.urls',namespace='goods')),

    #商家登入
    url(r'^seller/',include('seller.urls',namespace='seller')),

    url(r'^cart/',include('cart.urls',namespace='cart')), #购物车总路由

    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^openshop/',include('openshop.urls',namespace='openshop')),
    url(r'^store/',include('store.urls',namespace='store')),
    url(r'^admin/uploads/(?P<dir_name>[^/]+)$',upload_image,name="upload_image"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shops/store/urls.py
#coding utf-8
#mojun

from django.conf.urls import url
from.import views
urlpatterns=[
    url(r'^allstore/',views.allstore,name='allstore'),
    url(r'^store_page/(?P<openshop_id>[0-9]+)',views.store_page,name='store_page')

]

shops/users/urls.py
#coding utf-8
#mojun

from django.conf.urls import url

from.import views
urlpatterns = [
    url(r'^sign/',views.userSign,name="sign"), #注册会员
    url(r'^signdo/',views.userSigndo,name='signdo'),#注册的数据写进说一句库

    #email验证部分
    url(r'^UserEmail/',views.UserEmails,name='UserEmail'),

    url(r'^chakan_email/',views.chakan_email,name='chakan_email'),
    url(r'jihuo/',views.jihuo,name='jihuo'),
    url(r'^email_active/',views.email_active,name='email_active'),

    url(r'^login/',views.userLogin,name='login'),    #登入
    url(r'^logindo/',views.userLogindo,name='logindo'),
    url(r'^loginout/',views.loginout,name='loginout'),

    url(r'^main/',views.userMainPage,name='main'),   #登入成功的首页主页面


    # url(r'^carts/',views.userCart,name='carts'),   #购物车
    # url(r'^cartsdo',views.userCartsdo,name='cartsdo'),  #用户下单页面

    #商品详情页
    # url(r'^goods_introduce/',views.goods_introduce,name='goods_introduce'),

    #把数据传入商品详情页   一对一！
    # /(?P<seller_id>[0-9]+)这里加这个是为了对应index 加参数，seller_id 对应def goods_introduce(request,pk):
    #(request,pk,seller_id)  对应方法1
    url(r'^goods_introduce/(?P<pk>[0-9]+)',views.goods_introduce,name='goods_introduce'),

    url(r'^user_order/',views.user_order,name='user_order'),

    url(r'^user_base/',views.user_base,name='user_base'),


    url(r'users_orderdetails/(?P<pk>[0-9]+)/(?P<adress_id>[0-9]+)',views.users_orderdetails,name='users_orderdetails'),

    #收货
    url(r'^shouhuo/(?P<pk>[0-9]+)',views.shouhuo,name='shouhuo'),

    #个人资料修改
    url(r'^modifymessages/',views.modifymessages,name='modifymessages'),
    url(r'^modifymessagedo/',views.modifymessagedo,name='modifymessagedo'),

    #评论
    url(r'^commentgoodsadd/(?P<goods_id>[0-9]+)/(?P<seller_id>[0-9]+)',views.commentgoodsadd,name='commentgoodsadd'),
    
    url(r'^commentgoodsadddo/',views.commentgoodsadddo,name='commentgoodsadddo'),
    url(r'^get_valid_img/',views.get_valid_img,name='get_valid_img')



]

shops/templates/user_base/houtai_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'css/css/index.css' %}" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'js/js/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/main/mains.css' %}">
    <style>
        #cbbox_left{
            width: 100px;
        }
        #top_one ul{
           width: 1120px;
        }
    </style>
</head>

<body>
{#{% include 'templates/header.html' %}#}

{#<div class="top">#}
{#    <div class="top_s">#}
{#        <div class="top_p">#}
{#            <ul>#}
{##}
{#             <li><a href="{% url 'users:sign' %}">[注册有惊喜]</a></li>#}
{#             <li><a href="{% url 'cart:cartshow' %}">[购物车]</a></li>#}
{#             <li><a href="{% url 'users:sign' %}">[免费开店]</a></li>#}
{#            {% if request.session.uname %}#}
{#                  欢迎{{ request.session.uname }}登入成功 &nbsp;&nbsp;&nbsp;<a href="{% url 'users:sign' %}">切换账号</a>#}
{#            {% else %}#}
{#                <li><a href="{% url 'users:login' %}">[登入]</a></li>#}
{#             {% endif %}#}
{##}
{#        </ul>#}
{#        </div>#}
{#    </div>#}
{#    <div class="top_x">#}
{#        <div class="logo"><img src="{% static 'images/logo.png' %}" alt=""></div>#}
{#         <div id="ptp">#}
{#              <ul>#}
{#             <li><a href="{% url 'users:main' %}">首页<br/>Home</a></li>#}
{#             <li><a href="{% url 'users:main' %}">鲜果<br/>Fruit</a></li>#}
{#             <li><a href="{% url 'users:main' %}">会员中心<br/>VIP Club</a></li>#}
{##}
{##}
{#            </ul>#}
{##}
{#        </div>#}
{#    </div>#}
{##}
{#</div>#}







    <!-- 头部开始 -->
   <div class="header" id="top_one">
    <ul>
        <li><a href="{% url 'seller:sellerLogin' %}">[卖家入口]</a></li>
        <li><a href="{% url 'openshop:openshop' %}">[免费开店]</a></li>
         <li><a href="{% url 'cart:cartshow' %}">[进购物车]</a></li>
        {% if request.session.uname %}
            欢迎:{{ request.session.uname }} 登录成功  <a href="{% url 'users:sign' %}">切换账号</a>
        {% else %}
         <li><a href="{% url 'users:sign' %}">[注册惊喜]</a></li>
        <li><a href="{% url 'users:login' %}">[登录]</a></li>
        {% endif %}

    </ul>
    </div>


    <div class="header_logo">
            <div class="logo"></div>
            <div class="nav">
                <ul>
                    <li><a href="{% url 'users:main' %}">首页<br/>Home</a></li>
                    <li><a href="">鲜果<br/>Fruit</a></li>
                    <li><a href="{% url 'seller:store_list' %}">店铺<br/>Store</a></li>
                    <li><a href="{% url 'users:user_order' %}">会员中心<br/>VIP Club</a></li>
                </ul>
            </div>
    </div>
    <!-- 头部结束 -->





 <div class="center_box">
     <div id="cbbox_left">

     </div>
     <div class="cbbox_right">
        {% block bobx %}
        {% endblock %}
     </div>
 </div>
<div class="footer">网站版权归全球生鲜网所有</div>
</body>
</html>

shops/templates/user_base/shop.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'css/css/index.css' %}" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'js/js/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/main/mains.css' %}">
</head>
<style>
    .center_box p{
        font-size: 25px;
        font-family: 宋体 黑体;
        color: #4cae4c;
    }
</style>
<body>
    <!-- 头部开始 -->
   <div class="header">
    <ul>
        <li><a href="{% url 'seller:sellerLogin' %}">[卖家入口]</a></li>
        <li><a href="{% url 'openshop:openshop' %}">[免费开店]</a></li>
         <li><a href="{% url 'cart:cartshow' %}">[进购物车]</a></li>
        {% if request.session.uname %}
            欢迎:{{ request.session.uname }}
            <img src="{% static 'media/img/20181116192810.jpg' %}" width="30" height="30"/> 登录成功
            <a href="{% url 'users:sign' %}">切换账号</a>
        {% else %}
         <li><a href="{% url 'users:sign' %}">[注册惊喜]</a></li>
        <li><a href="{% url 'users:login' %}">[登录]</a></li>
        {% endif %}

    </ul>
    </div>


    <div class="header_logo">
            <div class="logo"></div>
            <div class="nav">
                <ul>
                    <li><a href="{% url 'users:main' %}">首页<br/>Home</a></li>
                    <li><a href="">鲜果<br/>Fruit</a></li>
                    <li><a href="{% url 'store:allstore' %}">店铺<br/>Store</a></li>
                    <li><a href="{% url 'users:user_order' %}">会员中心<br/>VIP Club</a></li>
                </ul>
            </div>
    </div>
    <!-- 头部结束 -->
    
 <div class="center_box">
 <p>免费注册店铺</p>
     <div class="cbbox_left">
{#         <ul>#}
{#             <li><a href="{% url 'users:user_order' %}">我的订单</a></li>#}
{#             <li><a href="#">密码修改</a></li>#}
{#             <li><a href="#">收货地址</a></li>#}
{#             <li><a href="{% url 'users:modifymessages' %}">个人资料</a></li>#}
{#         </ul>#}
     </div>
     <div class="cbbox_right">
        {% block bobx %}
        {% endblock %}
     </div>
 </div>
<div class="footer">网站版权归全球生鲜网所有</div>
</body>
</html>

shops/templates/user_base/shop_houtai.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'css/css/index.css' %}" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'js/js/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/main/mains.css' %}">
</head>
<style>
    .center_box p{
        font-size: 25px;
        font-family: 宋体 黑体;
        color: #4cae4c;
    }
</style>
<body>
    <!-- 头部开始 -->
   <div class="header">
{#    <ul>#}
{#        <li><a href="">[卖家入口]</a></li>#}
{#        <li><a href="">[免费开店]</a></li>#}
{#         <li><a href="{% url 'cart:cartshow' %}">[进购物车]</a></li>#}
{#        {% if request.session.uname %}#}
{#            欢迎:{{ request.session.uname }}#}
{#            <img src="{% static 'media/img/20181116192810.jpg' %}" width="30" height="30"/> 登录成功#}
{#            <a href="{% url 'users:sign' %}">切换账号</a>#}
{#        {% else %}#}
{#         <li><a href="{% url 'users:sign' %}">[注册惊喜]</a></li>#}
{#        <li><a href="{% url 'users:login' %}">[登录]</a></li>#}
{#        {% endif %}#}
{##}
{#    </ul>#}
    </div>


    <div class="header_logo">
            <div class="logo"></div>
            <div class="nav">
                <ul>
                    <li><a href="{% url 'users:main' %}">首页<br/>Home</a></li>
                    <li><a href="">鲜果<br/>Fruit</a></li>
                    <li><a href="{% url 'store:allstore' %}">店铺<br/>Store</a></li>
                    <li><a href="{% url 'users:user_order' %}">会员中心<br/>VIP Club</a></li>
                </ul>
            </div>
    </div>
    <!-- 头部结束 -->
    
 <div class="center_box">
 <p>卖家再开店>></p>
     <div class="cbbox_left">

     </div>
     <div class="cbbox_right">
        {% block bobx %}
        {% endblock %}
     </div>
 </div>
<div class="footer">网站版权归全球生鲜网所有</div>
</body>
</html>

shops/templates/user_base/user_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'css/css/index.css' %}" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'js/js/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/main/mains.css' %}">
</head>
<style>

</style>
<body>
{#{% include 'templates/header.html' %}#}

{#<div class="top">#}
{#    <div class="top_s">#}
{#        <div class="top_p">#}
{#            <ul>#}
{##}
{#             <li><a href="{% url 'users:sign' %}">[注册有惊喜]</a></li>#}
{#             <li><a href="{% url 'cart:cartshow' %}">[购物车]</a></li>#}
{#             <li><a href="{% url 'users:sign' %}">[免费开店]</a></li>#}
{#            {% if request.session.uname %}#}
{#                  欢迎{{ request.session.uname }}登入成功 &nbsp;&nbsp;&nbsp;<a href="{% url 'users:sign' %}">切换账号</a>#}
{#            {% else %}#}
{#                <li><a href="{% url 'users:login' %}">[登入]</a></li>#}
{#             {% endif %}#}
{##}
{#        </ul>#}
{#        </div>#}
{#    </div>#}
{#    <div class="top_x">#}
{#        <div class="logo"><img src="{% static 'images/logo.png' %}" alt=""></div>#}
{#         <div id="ptp">#}
{#              <ul>#}
{#             <li><a href="{% url 'users:main' %}">首页<br/>Home</a></li>#}
{#             <li><a href="{% url 'users:main' %}">鲜果<br/>Fruit</a></li>#}
{#             <li><a href="{% url 'users:main' %}">会员中心<br/>VIP Club</a></li>#}
{##}
{##}
{#            </ul>#}
{##}
{#        </div>#}
{#    </div>#}
{##}
{#</div>#}




    <!-- 头部开始 -->
   <div class="header">
    <ul>
        <li><a href="{% url 'seller:sellerLogin' %}">[卖家入口]</a></li>
        <li><a href="{% url 'openshop:openshop' %}">[免费开店]</a></li>
         <li><a href="{% url 'cart:cartshow' %}">[进购物车]</a></li>
        {% if request.session.uname %}
            欢迎:{{ request.session.uname }}
            <img src="{% static 'media/img/20181116192810.jpg' %}" width="30" height="30"/> 登录成功
            <a href="{% url 'users:sign' %}">切换账号</a>
        {% else %}
         <li><a href="{% url 'users:sign' %}">[注册惊喜]</a></li>
        <li><a href="{% url 'users:login' %}">[登录]</a></li>
        {% endif %}

    </ul>
    </div>


    <div class="header_logo">
            <div class="logo"></div>
            <div class="nav">
                <ul>
                    <li><a href="{% url 'users:main' %}">首页<br/>Home</a></li>
                    <li><a href="{% url 'goods:goodslist' %}">鲜果<br/>Fruit</a></li>
                    <li><a href="{% url 'store:allstore' %}">店铺<br/>Store</a></li>
                    <li><a href="{% url 'users:user_order' %}">会员中心<br/>VIP Club</a></li>
                </ul>
            </div>
    </div>
    <!-- 头部结束 -->


 <div class="center_box">
     <div class="cbbox_left">
         <ul>
             <li><a href="{% url 'users:user_order' %}">我的订单</a></li>
             <li><a href="#">密码修改</a></li>
             <li><a href="{% url 'order:order_adress' %}">收货地址</a></li>
             <li><a href="{% url 'users:modifymessages' %}">个人资料</a></li>
         </ul>
     </div>
     <div class="cbbox_right">
        {% block bobx %}
        {% endblock %}
     </div>
 </div>
<div class="footer">网站版权归全球生鲜网所有</div>
</body>
</html>