shops/cart/urls.py
#coding utf-8
#mojun

from django.conf.urls import url
from.import views

urlpatterns=[

    url(r'^cartadd/',views.cartadd,name='cartadd'),
    url(r'^cartshow/',views.cartshow,name='cartshow'),
    # url(r'^deletcart/(?P<pk>[0-9]+)',views.deletcart,name='deletcart'),
    #ajaxc
    url(r'^delcar/',views.delcar,name='delcar'),
    url(r'^changenum/',views.changenum,name='changenum'),
    url(r'^jiannum/',views.jiannum,name='jiannum'),



    url(r'^clearcart/',views.clearcart,name='clearcart'),

    #购物车的商品数量的加减，商品小计 ，商品总计
    url(r'^decgoodsnum/(?P<pk>[0-9]+)',views.decgoodsnum,name='decgoodsnum'),
    url(r'^addgoodsnum/(?P<pk>[0-9]+)',views.addgoodsnum,name='addgoodsnum'),


]

shops/goods/urls.py
#coding utf-8
#mojun

from django.conf.urls import url
from.import views

urlpatterns =[
    url(r'^goodsadd/$',views.goodsadd,name='goodsadd'),
    url(r'^goodstypeadd/',views.goodstypeadd,name='goodstypeadd'),
    url(r'^goodstypeaddDo/',views.goodstypeaddDo,name='goodstypeaddDo'),

    url(r'^goodsShow/$',views.goodsShow,name='goodsShow'),
    url(r'^delettype/(?P<pk>[0-9]+)',views.delettype,name='delettype'),
    url(r'^modlytype/(?P<pk>[0-9]+)',views.modlytype,name='modlytype'),
    url(r'^goodsmodlyDo/',views.goodsmodlyDo,name='goodsmodlyDo'),

    #商品进数据库
    url(r'^goodsadddo/',views.goodsadddo,name='goodsadddo'),


    url(r'^goodslist_show/',views.goodslist_show,name='goodslist_show'),

    url(r'^deletgoods/(?P<pk>[0-9]+)',views.deletgoods,name='deletgoods'),
    url(r'^modlygoods/(?P<pk>[0-9]+)',views.modlygoods,name='modlygoods'),

    url(r'^updatagoodsadddo/',views.updatagoodsadddo,name='updatagoodsadddo'),

    #鲜果列表
    url(r'^goodslist/',views.goodslist,name='goodslist'),
    url(r'^goodslist1/(?P<pk>[0-9]+)',views.goodslist1,name='goodslist1'),
    url(r'^goodslistss/(?P<type_id>[0-9]+)',views.goodslistss,name='goodslistss'),
    
    #商品下架
    url(r'^ishowx/(?P<pk>[0-9]+)',views.ishowx,name='ishowx'),
    #商品上架
    url(r'^ishows/(?P<pk>[0-9]+)',views.ishows,name='ishows'),




]

shops/seller/urls.py
#coding utf-8
#mojun
from django.conf.urls import url

from.import views

urlpatterns = [
    # 商家登入
    url(r'^sellerLogin/$', views.sellerLogin, name='sellerLogin'),
    url(r'^sellerLogindo/$', views.sellerLogindo, name='sellerLogindo'),
    url(r'^sellerout/',views.sellerout,name='sellerout'),

    url(r'^sellerMina/(?P<pk>[0-9]+)',views.sellerMina,name='sellerMina'),
    url(r'^showorder/',views.showorder,name='showorder'),

    #会员中心的会员列表
    url(r'^huiyuan/',views.huiyuan,name='huiyuan'),

    url(r'^show_xiangqing/(?P<pk>[0-9]+)/(?P<adress_id>[0-9]+)',views.show_xiangqing,name='show_xiangqing'),
    # url(r'^show_xiangqing/',views.show_xiangqing,name='show_xiangqing')

#收货
    url(r'^fahuo/(?P<pk>[0-9]+)',views.fahuo,name='fahuo'),

    url(r'^seller_chakan_comment/(?P<pk>[0-9]+)',views.seller_chakan_comment,name='seller_chakan_comment'),

    #卖家店铺
    url(r'^store_list/',views.store_list,name='store_list'),


    #已有店铺的卖家开店
    url(r'^store/',views.store,name='store'),

    #卖家再开店的数据写进openshopdata数据库
    url(r'^storedo',views.storedo,name='storedo'),

    #邮件的发送
    url(r'^sendemail/(?P<pk>[0-9]+)',views.sendemail,name='sendemail'),
    url(r'^sendemaildo/',views.sendemaildo,name='sendemaildo'),



    #后台权限分配
    url(r'^management/',views.management,name='management'),
    url(r'^poweradd/',views.poweradd,name='poweradd'),
    url(r'^dopower/',views.dopower,name='dopower'),
    url(r'^delpower/',views.delpower,name='delpower'),



    # 后台角色分配
    url(r'^roles/', views.roles, name='roles'),
    url(r'^roleadd/', views.roleadd, name='roleadd'),
    url(r'^dorole/', views.dorole, name='dorole'),
    url(r'^delrole/', views.delrole, name='delrole')





]

shops/shops/urls.py
from django.conf.urls import url,include
from.upload import upload_image
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^User/',include('users.urls',namespace='users')),
    url(r'^Goods/',include('goods.urls',namespace='goods')),

    #商家登入
    url(r'^seller/',include('seller.urls',namespace='seller')),

    url(r'^cart/',include('cart.urls',namespace='cart')), #购物车总路由

    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^openshop/',include('openshop.urls',namespace='openshop')),
    url(r'^store/',include('store.urls',namespace='store')),
    url(r'^admin/uploads/(?P<dir_name>[^/]+)$',upload_image,name="upload_image"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shops/store/urls.py
#coding utf-8
#mojun

from django.conf.urls import url
from.import views
urlpatterns=[
    url(r'^allstore/',views.allstore,name='allstore'),
    url(r'^store_page/(?P<openshop_id>[0-9]+)',views.store_page,name='store_page')

]

shops/users/urls.py
#coding utf-8
#mojun

from django.conf.urls import url

from.import views
urlpatterns = [
    url(r'^sign/',views.userSign,name="sign"), #注册会员
    url(r'^signdo/',views.userSigndo,name='signdo'),#注册的数据写进说一句库

    #email验证部分
    url(r'^UserEmail/',views.UserEmails,name='UserEmail'),

    url(r'^chakan_email/',views.chakan_email,name='chakan_email'),
    url(r'jihuo/',views.jihuo,name='jihuo'),
    url(r'^email_active/',views.email_active,name='email_active'),

    url(r'^login/',views.userLogin,name='login'),    #登入
    url(r'^logindo/',views.userLogindo,name='logindo'),
    url(r'^loginout/',views.loginout,name='loginout'),

    url(r'^main/',views.userMainPage,name='main'),   #登入成功的首页主页面


    # url(r'^carts/',views.userCart,name='carts'),   #购物车
    # url(r'^cartsdo',views.userCartsdo,name='cartsdo'),  #用户下单页面

    #商品详情页
    # url(r'^goods_introduce/',views.goods_introduce,name='goods_introduce'),

    #把数据传入商品详情页   一对一！
    # /(?P<seller_id>[0-9]+)这里加这个是为了对应index 加参数，seller_id 对应def goods_introduce(request,pk):
    #(request,pk,seller_id)  对应方法1
    url(r'^goods_introduce/(?P<pk>[0-9]+)',views.goods_introduce,name='goods_introduce'),

    url(r'^user_order/',views.user_order,name='user_order'),

    url(r'^user_base/',views.user_base,name='user_base'),


    url(r'users_orderdetails/(?P<pk>[0-9]+)/(?P<adress_id>[0-9]+)',views.users_orderdetails,name='users_orderdetails'),

    #收货
    url(r'^shouhuo/(?P<pk>[0-9]+)',views.shouhuo,name='shouhuo'),

    #个人资料修改
    url(r'^modifymessages/',views.modifymessages,name='modifymessages'),
    url(r'^modifymessagedo/',views.modifymessagedo,name='modifymessagedo'),

    #评论
    url(r'^commentgoodsadd/(?P<goods_id>[0-9]+)/(?P<seller_id>[0-9]+)',views.commentgoodsadd,name='commentgoodsadd'),
    
    url(r'^commentgoodsadddo/',views.commentgoodsadddo,name='commentgoodsadddo'),
    url(r'^get_valid_img/',views.get_valid_img,name='get_valid_img')



]

shops/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>生鲜网页架构</title>
    <link rel="stylesheet" href="{% static 'css/main/mains.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link type="text/css" href="{% static 'css/css/index.css' %}" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'js/js/jquery.min.js' %}"></script>
</head>
<body>
{% include 'header.html' %}
{% block content %}

{% endblock %}
{% include 'footer.html' %}
</body>
</html>

shops/templates/footer.html
<div class="foot">
    此网站版权归全球生鲜所有
</div>

shops/templates/header.html
{% load static %}
{#<div class="top">#}
{#    <div class="top_s">#}
{#        <div class="top_p">#}
{#            <ul>#}
{##}
{#             <li><a href="{% url 'users:sign' %}">[注册有惊喜]</a></li>#}
{#             <li><a href="{% url 'cart:cartshow' %}">[购物车]</a></li>#}
{#             <li><a href="{% url 'users:sign' %}">[免费开店]</a></li>#}
{#            {% if request.session.uname %}#}
{#                {% for foo in aa %}#}
{#                  欢迎{{ request.session.uname }}<img src="{{foo.user_photo}}" width="30" height="30"/>登入成功#}
{#                {% endfor %}#}
{#                <a href="{% url 'users:sign' %}">切换账号</a>#}
{#            {% else %}#}
{#                <li><a href="{% url 'users:login' %}">[登入]</a></li>#}
{#             {% endif %}#}
{##}
{#        </ul>#}
{#        </div>#}
{#    </div>#}
{#    <div class="top_x">#}
{#        <div class="logo"><img src="{% static 'images/logo.png' %}" alt=""></div>#}
{#         <div id="ptp">#}
{#              <ul>#}
{#             <li><a href="{% url 'users:main' %}">首页<br/>Home</a></li>#}
{#             <li><a href="{% url 'users:main' %}">鲜果<br/>Fruit</a></li>#}
{#             <li><a href="{% url 'users:user_order' %}">会员中心<br/>VIP Club</a></li>#}
{##}
{##}
{#            </ul>#}
{##}
{#        </div>#}
{#    </div>#}
{##}
{#</div>#}




    <!-- 头部开始 -->
   <div class="header">
    <ul>
        <li><a href="{% url 'seller:sellerLogin' %}">[卖家入口]</a></li>
        <li><a href="{% url 'openshop:openshop' %}">[免费开店]</a></li>
         <li><a href="{% url 'cart:cartshow' %}">[进购物车]</a></li>
        {% if request.session.uname %}
            欢迎:{{ request.session.uname }}
{#            {% for foo in aa %}#}
            <img src="{% static 'media/img/20181116192810.jpg' %}" width="30" height="30"/>登录成功
{#             {% endfor %}#}
            <a href="{% url 'users:loginout' %}">切换账号</a>
        {% else %}
         <li><a href="{% url 'users:sign' %}">[注册惊喜]</a></li>
        <li><a href="{% url 'users:login' %}">[登录]</a></li>
        {% endif %}

    </ul>
    </div>


    <div class="header_logo">
            <div class="logo"></div>
            <div class="nav">
                <ul>
                    <li><a href="{% url 'users:main' %}">首页<br/>Home</a></li>
                    <li><a href="{% url 'goods:goodslist' %}">鲜果<br/>Fruit</a></li>
                    <li><a href="{% url 'store:allstore' %}">店铺<br/>Store</a></li>
                    <li><a href="{% url 'users:user_order' %}">会员中心<br/>VIP Club</a></li>
                </ul>
            </div>
    </div>
    <!-- 头部结束 -->